### PR TITLE
Tor instances configurable in run command

### PR DESCRIPTION
**Pull request by JKamsker**
Can now specify tor instances in run command like so: 
`docker run --rm -e "TOR_INSTANCES=10" jkamsker/multitor`

### CODE REVIEW

**Comment by JKamsker** [comment]
@blacklist-arcc Ping! :D

**Comment by FLX-0x00** [comment]
Keep calm :)

**Comment by JKamsker** [comment]
Sry :D
I was just so excited to get it merged xD

**Comment by JKamsker** [comment]
Urrm...maybe we should extend the docs mentioning this new option....

**Comment by FLX-0x00** [comment]
PR welcome =)

**Pull request merged**
